export const serviceTemplate = `
/**
 * Auto generated by GraphaX Extension
 */
%imports%

/**
 * %serviceNameToTitleCase% service class to query an endpoint with an ApolloClient 
 */
export class %serviceNameToTitleCase%Service {

    constructor(private _client){}

    %functions%

};
`;

export const serviceFunctionTemplate = `
    get%functionName%(args:schemaTypes.%inputType%){
        this._client.%functionType%({
            %requestType%: %request%,
            arguments: args
        }).then((data:schemaTypes.%requestType%) => {return data.%returnType%})
        .catch(error => {return error});
    }
`;
